/// sync_server.dart — Local shelf HTTP server on the Owner's phone
///
/// Endpoints:
///   POST /sync   — receive data from employees (invoices + activity log)
///   GET  /config — send store configuration
///
/// Security:
///   - Bearer token authentication on all endpoints
///   - Token is generated by the Owner and shared via QR code
///
/// Discovery:
///   - NSD/mDNS registration for local network discovery
///   - QR code contains IP directly for simplicity
///
/// Paper Ledger design.
library;

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:shelf/shelf.dart' as shelf;
import 'package:shelf/shelf_io.dart' as shelf_io;
import 'package:shelf_router/shelf_router.dart';

/// Callback type for receiving sync data on the server side.
typedef SyncDataCallback = Future<Map<String, dynamic>> Function(Map<String, dynamic> data);

/// Callback for config requests.
typedef ConfigCallback = Future<Map<String, dynamic>> Function();

/// Local HTTP server running on the Owner's device.
///
/// Employees connect to this server via local Wi-Fi (no internet needed).
class SyncServer {
  SyncServer({
    required String authToken,
    required SyncDataCallback onSyncData,
    required ConfigCallback onConfigRequest,
    int port = 8080,
    String? serviceName,
  })  : _authToken = authToken,
        _onSyncData = onSyncData,
        _onConfigRequest = onConfigRequest,
        _port = port,
        _serviceName = serviceName ?? 'FaturaSync';

  final String _authToken;
  final SyncDataCallback _onSyncData;
  final ConfigCallback _onConfigRequest;
  final int _port;
  final String _serviceName;

  HttpServer? _server;
  bool _isRunning = false;

  /// Whether the server is currently running.
  bool get isRunning => _isRunning;

  /// The port the server is listening on.
  int get port => _port;

  /// Get the server's local IP address.
  Future<String> get localIp async {
    final interfaces = await NetworkInterface.list(
      type: InternetAddressType.IPv4,
      includeLinkLocal: false,
    );
    for (final iface in interfaces) {
      for (final addr in iface.addresses) {
        if (!addr.isLoopback) {
          return addr.address;
        }
      }
    }
    return '127.0.0.1';
  }

  /// Start the HTTP server.
  Future<String> start() async {
    if (_isRunning) return localIp;

    final ip = await localIp;
    final router = Router();

    // POST /sync — receive data from employees
    router.post('/sync', (shelf.Request request) async {
      // Auth check
      final authHeader = request.headers['authorization'];
      if (authHeader == null || authHeader != 'Bearer $_authToken') {
        return shelf.Response(401,
            body: jsonEncode({'error': 'غير مصرح'}),
            headers: {'Content-Type': 'application/json'});
      }

      try {
        final body = await request.readAsString();
        final data = jsonDecode(body) as Map<String, dynamic>;
        final result = await _onSyncData(data);

        return shelf.Response.ok(
          jsonEncode(result),
          headers: {'Content-Type': 'application/json'},
        );
      } catch (e) {
        return shelf.Response(400,
            body: jsonEncode({'error': 'بيانات غير صحيحة: $e'}),
            headers: {'Content-Type': 'application/json'});
      }
    });

    // GET /config — send store configuration
    router.get('/config', (shelf.Request request) async {
      // Auth check
      final authHeader = request.headers['authorization'];
      if (authHeader == null || authHeader != 'Bearer $_authToken') {
        return shelf.Response(401,
            body: jsonEncode({'error': 'غير مصرح'}),
            headers: {'Content-Type': 'application/json'});
      }

      try {
        final config = await _onConfigRequest();
        return shelf.Response.ok(
          jsonEncode(config),
          headers: {'Content-Type': 'application/json'},
        );
      } catch (e) {
        return shelf.Response(500,
            body: jsonEncode({'error': 'خطأ في الإعدادات: $e'}),
            headers: {'Content-Type': 'application/json'});
      }
    });

    // GET /health — no auth, for connection testing
    router.get('/health', (shelf.Request request) {
      return shelf.Response.ok(
        jsonEncode({'status': 'ok', 'service': _serviceName}),
        headers: {'Content-Type': 'application/json'},
      );
    });

    // Cascade handler with logging.
    final handler = const shelf.Pipeline()
        .addMiddleware(_corsMiddleware())
        .addMiddleware(_loggingMiddleware())
        .addHandler(router.call);

    _server = await shelf_io.serve(handler, InternetAddress.anyIPv4, _port);
    _isRunning = true;

    debugPrint('✅ SyncServer running on $ip:$_port');
    return ip;
  }

  /// Stop the server.
  Future<void> stop() async {
    if (!_isRunning) return;

    await _server?.close(force: true);
    _server = null;
    _isRunning = false;
    debugPrint('🛑 SyncServer stopped');
  }

  /// CORS middleware for cross-origin requests.
  shelf.Middleware _corsMiddleware() {
    return (shelf.Handler innerHandler) {
      return (shelf.Request request) async {
        if (request.method == 'OPTIONS') {
          return shelf.Response.ok(null, headers: {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
            'Access-Control-Allow-Headers': 'Authorization, Content-Type',
          });
        }
        final response = await innerHandler(request);
        return response.change(headers: {
          'Access-Control-Allow-Origin': '*',
        });
      };
    };
  }

  /// Simple logging middleware.
  shelf.Middleware _loggingMiddleware() {
    return (shelf.Handler innerHandler) {
      return (shelf.Request request) async {
        final startTime = DateTime.now();
        final response = await innerHandler(request);
        final duration = DateTime.now().difference(startTime);
        debugPrint(
            '📡 ${request.method} ${request.requestedUri.path} → ${response.statusCode} (${duration.inMilliseconds}ms)');
        return response;
      };
    };
  }
}

/// Minimal debug print wrapper.
void debugPrint(Object? message) {
  // ignore: avoid_print
  print(message);
}